### ISSUE TITLE
Can Redex express non-regular patterns?

### ISSUE THREAD

**Issue by leafac** [nuprl/website#122]
[PLT Redex FAQ](http://prl.ccs.neu.edu/blog/2017/09/25/plt-redex-faq/) reads:

> Q. What can patterns not express? […] Non-regular patterns. For example, one non-regular pattern is “all lists that contain some number of integers followed by the same number of strings”.

But I believe the `(integer ..._n string ..._n)` pattern matches the description exactly:

```racket
#lang racket
(require redex)

(define-language L)

(redex-match? L (integer ..._n string ..._n) (term ())) ;; => #t
(redex-match? L (integer ..._n string ..._n) (term (1))) ;; => #f
(redex-match? L (integer ..._n string ..._n) (term (1 "a"))) ;; => #t
(redex-match? L (integer ..._n string ..._n) (term (1 2 "a"))) ;; => #f
```

**Comment by bennn** [comment]
Oops, you're right. I guess redex can express some non-regular patterns.

How about I change the post to:

> ... cannot express some non-regular patterns, for example "all lists that contain `N` strings followed by `N^2` integers"

**Comment by leafac** [comment]
I’m afraid not even that is true, due to the `side-condition` pattern:

```racket
#lang racket
(require redex)
(define-language non-regular-tree
  [n-strings-followed-by-n^2-integers ::=
                                      (side-condition (string_ ... integer_ ...)
                                                      (= (expt (length (term (string_ ...))) 2)
                                                         (length (term (integer_ ...)))))])
(redex-match? non-regular-tree n-strings-followed-by-n^2-integers (term ())) ;; => #t
(redex-match? non-regular-tree n-strings-followed-by-n^2-integers (term ("a"))) ;; => #f
(redex-match? non-regular-tree n-strings-followed-by-n^2-integers (term ("a" 1))) ;; => #t
(redex-match? non-regular-tree n-strings-followed-by-n^2-integers (term ("a" 1 2))) ;; => #f
(redex-match? non-regular-tree n-strings-followed-by-n^2-integers (term ("a" "b" 1 2 3))) ;; => #f
(redex-match? non-regular-tree n-strings-followed-by-n^2-integers (term ("a" "b" 1 2 3 4))) ;; => #t
(redex-match? non-regular-tree n-strings-followed-by-n^2-integers (term ("a" "b" 1 2 3 4 5))) ;; => #f
```

You might be thinking: “Leandro, you’re unquoting back to Racket, you’re cheating!” And I kind of am, but the [Redex documentation](https://docs.racket-lang.org/redex/The_Redex_Reference.html#%28form._%28%28lib._redex%2Freduction-semantics..rkt%29._define-language%29%29) agrees with me:

> The define-language form supports the definition of recursive patterns, much like a BNF, but for regular-tree grammars. It goes beyond their expressive power, however, because repeated name, in-hole, and side-condition patterns can restrict matches in complex ways.

Maybe the article we’re talking about isn’t the right place to bring up all these subtleties, since it’s targeted at beginners, but I believe it deserves at least an explanatory footnote to avoid misrepresenting Redex.

**Comment by bennn** [comment]
Cool, I didn't know that.

What about changing the words to sound more like the first bullet?

> ... Some non-regular patterns (named dots `..._N` or `define-language` with a side condition might be able to help)

**Comment by leafac** [comment]
Sounds good. By the way, I appreciate you discussing Redex **limitations** as well as features in the article. Too often people focus just on the latter.
