### ISSUE TITLE
New Members 2018

### ISSUE THREAD

**Issue by bennn** [nuprl/website#132]
Need to add: @ulysses4ever @julbinb @alexiturcotte and @emarteca

**Comment by mhyee** [comment]
We should also make sure they're added to the GitHub organization, mailing lists, etc. Did we add Jason to the appropriate lists?

**Comment by LeifAndersen** [comment]
@julbinb is the person who is supposed to manage this page. Adding her.

**Comment by bennn** [comment]
I've:

-  invited Artem, Julia, Alexi, Jason, and Ellen to the GitHub organization.
- sent mail to Ben Chung asking to add Jason to the prl-students list

**Comment by julbinb** [comment]
@ulysses4ever and myself have been added.
