### ISSUE TITLE
Remove G+ social button 

### ISSUE THREAD

**Issue by ulysses4ever** [nuprl/website#150]
[Google: We are shutting down Google+ for consumers.](https://www.blog.google/technology/safety-security/project-strobe/amp/)

Although, it takes 10 months for them, I think we can do this right now.

**Comment by bennn** [comment]
The button is gone, right?

**Comment by mhyee** [comment]
We still have code that loads JavaScript for the Google+ button: https://github.com/nuprl/website/blob/68ff08c4d4abdbd867ad91ee89fa84ea2104b444/blog/_src/post-template.html#L10

You can also see it in the rendered HTML.

Do we define that function somewhere else? Or is deleting that line everything we need to do?

**Comment by bennn** [comment]
Ok. I still don't see the button in the rendered HTML (neither locally nor via `prl.ccs.neu.edu`, but let's remove that line.

I don't see anything else in this repo that needs to be deleted (grepped for `google` and `plusone`)

**Comment by mhyee** [comment]
I think it's only on blog pages, and not the home page:

![image](https://user-images.githubusercontent.com/547059/69092563-927de700-0a44-11ea-9a7d-6a2d9d13b1f9.png)

Either way, thanks for taking care of it!

**Comment by bennn** [comment]
I don't see anything in rendered blog pages
