### ISSUE TITLE
Order of seminars

### ISSUE THREAD

**Issue by mhyee** [nuprl/website#167]
The list of seminars is in reverse chronological order, which gives us:

- Far future
- Near future
- Next seminar
- *Last seminar*
- *Near past*
- *Far past*

Meaning you have to scroll partway down the page to find the next upcoming seminar. At least past seminars are greyed out.

It would make more sense to split the list into upcoming seminars and past seminars. Upcoming seminars should be in *chronological order* so the next seminar is first.

Since the site is generated by a script, it should be straightforward to implement this. And we use Travis CI for our builds, which supports [cron jobs](https://docs.travis-ci.com/user/cron-jobs/).

**Comment by bennn** [comment]
Are you planning to implement this?

(I would be happy to implement it, but I think it would be best for the future of the site if I'm just around to answer questions for whoever wants to try it.)
