### ISSUE TITLE
Publication page needs better structure

### ISSUE THREAD

**Issue by gasche** [nuprl/website#20]
(cc: @schuster)

I decided to do my part to help by adding to the Publication page the two publications of our lab at POPL'17 (one by me, one by Stephen, Alex and Ben G.). (I'll actually wait for the URL of @stchang's definitive version to submit a PR.) However, the publication page today is a bit unwieldy.

### Old stuff

There is a (helpful) comment that we should only include publications where one author is a member of the lab at the time of publication (more precisely, it would make sense to consider publications with one author affiliated to the lab), but that old publications may not respect this rule. Why not fix old publications by enforcing the rule? It's easy to find out when people joined the lab, and to cut the publication list before that (and we can use the affiliations in the PDFs to decide corner cases).

### Weird structure

The list of publications is currently defined as:

```racket
   (flatten (list mf-pubs
                  old-site-pubs
                  amal-pubs
                  jan-pubs
                  mitch-pubs
                  olin-pubs
                  will-pubs)))
```

where should the new papers go? I think that we could/should avoid this delicate question in the future, by moving all "old" publications to a `publications-old.rkt` file that would only export `old-pubs` (possibly by concatenating by-faculty-author lists internally), and having a single list of "new" publications that contains all new publications. This would also make `publications.rkt` less long and easier to edit for newcomers. Of course, that means we lose the easy way to single out publications of a specific faculty member, but (1) I don't think we actually need to do this, (2) it's going to be delicate again if two faculty publish a paper together and (3) we can always grep on the author names after the fact.

**Comment by schuster** [comment]
Regarding old stuff: that hasn't been done only because it takes a fair amount of effort to do that for every paper and every author, and I've been focusing on higher-priority tasks whenever I carve out time to work on this page.

Regarding the structure, how about this policy: just have one big list of publications, sorted in reverse chronological order? That way all new edits are at the top of the page, and the messy old publications that might be removed are way at the bottom where they don't matter. A comment on the page could easily let newcomers know where to put their additions. Thoughts?

**Comment by schuster** [comment]
(Edit: gave this issue a more descriptive title)

P.S. This is good timing, as I was already planning on updating this page this week, anyway.

**Comment by gasche** [comment]
I'm not sure carving old publications is so much work (assuming we know in which years faculty members joined), and I did not intend to mean that you in particular should do this work (apologies for being unclear). I'm more interested in whether, in principle, this is an idea people agree on -- I or someone else may volunteer to do it one day.

Your compromise proposal sounds good. If you do the structural work with an empty list (or a merge of existing lists or whatever you think is best), I would be glad to submit a PR with the two new publications there.

**Comment by schuster** [comment]
I'd have to look back at the list again, but I'm not sure that assumption holds - we'd have to do some extra work to figure out when various faculty or students were here. But yes, I would generally agree to that principle.

I'll do the merging work on the existing faculty list sometime in the next few days, then we can move forward with the rest.

**Comment by bennn** [comment]
The new publications page will have one long, chronologically-sorted list?
(That sounds good.)

**Comment by schuster** [comment]
Yes, with the caveat that within a single year, papers might not be sorted because we don't have that information. There are only so many papers per year anyway, though, so they wouldn't be hard to find.
