### ISSUE TITLE
Update copyright year?

### ISSUE THREAD

**Issue by julbinb** [nuprl/website#217]
Currently, the website footer says: "© Copyright Programming Research Laboratory 2015-2016".

I don't know much about copyrights, but should not it be 2015-2019?

**Comment by julbinb** [comment]
@michaelballantyne

**Comment by ulysses4ever** [comment]
I'd say, yes.

**Comment by michaelballantyne** [comment]
Done in c2ce062d6207a7f7db1e68497dee23fa77d359ef
