### ISSUE TITLE
catchexception signals exception

### ISSUE THREAD

**Issue by jasonhemann** [nuprl/website#247]
[Link at bottom of page](https://prl.ccs.neu.edu/new-members.html#navbar:~:text=made%20by%20Catchexception%20s.r.o.) to catchexception.cz is a dead link. Unsure where to redirect.

**Comment by ulysses4ever** [comment]
Good catch !

I asked Jan (who supposedly hired them). He guess they want it of business and suggests removing the hyperlink but leaving the name in place.

**Comment by bennn** [comment]
#248
