### ISSUE TITLE
Update Contacts for 2020-2021

### ISSUE THREAD

**Issue by julbinb** [nuprl/website#252]
New roles are [here](https://docs.google.com/document/d/1mzs877pWo4kWFwnIY1C5rHedugTQopH22N7s4buxXd0/edit?usp=sharing)

**Comment by ulysses4ever** [comment]
Am I correct that updating the Contacts page is under webmaster's jurisdiction?

**Comment by julbinb** [comment]
I believe so.

**Comment by ulysses4ever** [comment]
Ping @LeifAndersen. 
Our website's Contacts page vastly diverged from reality. Leif, could you, please, act on this?
If it's someone else's responsibility, I'm deeply sorry. But I'd like to know who this person is, if possible.

**Comment by ulysses4ever** [comment]
Will be solved by #265. Thanks, @julbinb, for leading this.

**Comment by ulysses4ever** [comment]
Fixed with c8c5479a.
