### ISSUE TITLE
Adding checks for pull-requests in GitHub actions

### ISSUE THREAD

**Issue by julbinb** [nuprl/website#275]
It would be good to run some checks on pull-request like we used to with Travis. Perhaps build the website without deploying?

**Comment by LeifAndersen** [comment]
Building the website without deploying it is easy enough to do. But is that the only check you had in mind?

**Comment by LeifAndersen** [comment]
Anyway, if that's all you wanted, I just added a workflow that I 'think' should do it.

**Comment by LeifAndersen** [comment]
If it was the default then it was just that, attempting to build. (Since we don't have any tests, unless you want to make some. ;) )

Anyway, I'ma close this now if that's okay?

**Comment by julbinb** [comment]
Yes, sure thing :)

**Comment by ulysses4ever** [comment]
Speaking about Travis: maybe we should remove its file from the repo?

**Comment by LeifAndersen** [comment]
Probably a good idea. Done.

**Comment by ulysses4ever** [comment]
Amazing, thanks!
