### ISSUE TITLE
Why is teaching faculty not on the website?

### ISSUE THREAD

**Issue by julbinb** [nuprl/website#279]
Is there a reason why we don't put teaching faculty on the website? Their courses are listed on the teaching page, but they are not on the people page.

**Comment by mfelleisen** [comment]
I asked for this when we launched. I treat them as equals in my group. It's a shame that we needed N years to attach them.

**Comment by LeifAndersen** [comment]
Wait, aren't they already on there? (At least the ones I'm aware of are there.)

(Or are you suggesting we have them in a dedicated section?)

**Comment by julbinb** [comment]
Oh, my bad! Indeed, I overlooked. Closing.
