### ISSUE TITLE
2021 update for contact page

### ISSUE THREAD

**Issue by ulysses4ever** [nuprl/website#280]
The contact page seems to reflect 2020 state and needs an update. According to [the wiki page on Lab roles][wiki] this is the job of the contact  manager, so ping @camoy.

[wiki]: https://github.com/nuprl/website/wiki/Lab-Roles#contact-managers

**Comment by donald-pinckney** [comment]
In progress in #281

**Comment by donald-pinckney** [comment]
Yeah I don't have write access, so someone can merge the PR?

**Comment by ulysses4ever** [comment]
I merged it, thank you! But that's another issue actually: people page and contacts page are different zones or responsibility!

**Comment by ulysses4ever** [comment]
It seems to me that is also Cameron's job to add push rights to you 🙃

**Comment by donald-pinckney** [comment]
Ooopps, contact sounded too similar to people, didn't read carefully lol. And yes I got push rights now, so all good

**Comment by ulysses4ever** [comment]
What can I say: this issue was 200% effective!..

**Comment by camoy** [comment]
Done in #282.
