### ISSUE TITLE
Website build failure (on GH Actions)

### ISSUE THREAD

**Issue by ulysses4ever** [nuprl/website#286]
See https://github.com/nuprl/website/runs/4040450794?check_suite_focus=true

The error message is (I think):

```
The following out-of-date packages are listed as dependencies of tzinfo
and they will be automatically updated:
   base (have 7.2, need 7.5.0.7)
raco pkg install: package installed in a different scope
  package: base
  current scope: user
  installed in scope: installation
```

/cc @LeifAndersen @ytzi

**Comment by LeifAndersen** [comment]
I fixed this issue. Thanks for reporting it.

**Comment by ulysses4ever** [comment]
Thanks @LeifAndersen! For future reference, would be good to document (at least with a reference to the fixing commit) how you actually fixed it. That way next generations would have more chances for being able to fix similar issues.

**Comment by LeifAndersen** [comment]
Oh, sure. I just switched from installing racket from the Ubuntu repo's to using github actions: https://github.com/nuprl/website/blob/master/.github/workflows/build.yml#L12

The problem was that the ubuntu repo's version of racket didn't like installing packages in user space, which is where the package wanted to be installed.

**Comment by ulysses4ever** [comment]
Great, thanks a lot! I saw the commits adding the setup-racket action (4fb0e3a and the following) just couldn’t connect it to the problem. It makes more sense now. Do you mind commenting on #286 as well (wrt to how that problem was fixed)? I assume we’ll have to update to Racket 8 at some point, so it may be useful at some point.

**Comment by LeifAndersen** [comment]
I suspect (but am not 100% sure), that it's because of the switch to Racket 8, the FFI changed. Probably the easiest thing to do is use the BC build of racket 8. But if we do have to switch to the CS build, we'll probably have to modify the FFI blog post to not actually run any code.

**Comment by ulysses4ever** [comment]
Oh, right, that makes sense. Thanks again, Leif! I guess disable code running would be most appropriate going forward.

And I'm guessing this issue is not actually closed.

**Comment by LeifAndersen** [comment]
Good point, I reponed it.

**Comment by ulysses4ever** [comment]
This one is good I thought. Did you buy any change confused this with #287?

**Comment by LeifAndersen** [comment]
Oh, woops, I was on the wrong issue page. Yes, this one is good. re-re-re-re-closing. (Sorry about that.)
