### ISSUE TITLE
Publications page Fall 2021 update

### ISSUE THREAD

**Issue by ulysses4ever** [nuprl/website#291]
We need ICFP (that's only Zoe?) and OOPSLA (a lot) papers. Cc @katherine-hough

**Comment by ulysses4ever** [comment]
Actually, there's Matthias at ICFP too. And there are probably SE publications that I'm not aware of (e.g. Jon has an ICSE paper).

**Comment by katherine-hough** [comment]
I added Jon's 2021 ICSE paper when I updated the page over the summer.

I checked the accepted papers pages for ICST 2021, ISSTA 2021, ICSE 2021, ASE 2021, FSE 2021, POPL 2021, PLDI 2021, ECOOP 2021, and ICFP 2021; the dblp page for everyone in the lab that has one; and the publications page for all of the professors. 

Other than Zoe, are there any other lab members not on the People page that I should be checking for?

**Comment by ulysses4ever** [comment]
Looks great, thank you! I’m not aware of anything else.
