### ISSUE TITLE
Make the blog header title a link

### ISSUE THREAD

**Issue by maxsnew** [nuprl/website#30]
Just saw Gabriel's GC blog post on [HN](https://news.ycombinator.com/item?id=13104556) and I intuitively tried to press the "Inside PRL Reading between the Parentheses" text expecting it to take me to the list of blog posts, but it isn't actually a link.

I think I'll change it because the design made me feel like it should be a link and it's much bigger than the tiny "blog" link at the top.
Good idea? Bad idea? I'll do a pr later (or somebody else can go ahead and do if they feel like it).

**Comment by schuster** [comment]
Hmm... does this imply that the heading on all pages through the site should be links? They all have the same styling, but the link wouldn't take you anywhere for any of the other pages, and users probably wouldn't try to click it then, either. But I also don't see any harm in making them all links.

**Comment by maxsnew** [comment]
Yea it doesn't matter for the other pages because they don't have
"sub-pages" anyway. But if we added something like pages for individual
seminars it would make sense to do the same there.

-Max Stewart New
