### ISSUE TITLE
GH org: Lab members team is outdated

### ISSUE THREAD

**Issue by ulysses4ever** [nuprl/website#305]
(I didn't find a better place to raise this issue. I think it falls under the jurisdiction of the web master, so paging in @ytzi.)

The only team on the website is lab-members, and it has 56 members:
https://github.com/orgs/nuprl/teams/lab-members/members

At the same time, the GH org has 88 members. Having an up to date team for everyone is really handy when you want to share access to a private repo with all org members. So, I think we should maintain the team properly.

**Comment by arjunguha** [comment]
How about two teams: current members and alums?

**Comment by bennn** [comment]
@ulysses4ever @arjunguha I got an email from github this morning saying that I can no longer access `nuprl/amnesic`. Please re-add me to that repo.

**Comment by bennn** [comment]
I see ... #306 is the problem. Only the faculty have these permissions now.

**Comment by ulysses4ever** [comment]
@arjunguha RE: two teams. It looks fine but I'd lean towards less bureaucracy, not more: remember this thread started with the note that we can't properly attend to one team even. So, if we want to add a second team, it's good to have a clear idea of why. E.g. for the `lab-members` team, it's easy: it's the ability to share private repos with the whole PRL (at least, that was my use case when opening this ticket). For alumni, I'm less sure. But again, I'm fine with it.

Whatever is decided, we should not forget to update https://github.com/nuprl/website/wiki/Lab-Roles

**Comment by mfelleisen** [comment]
Why should faculty be the owners? The beneficiaries of a great web site are the PhD students who graduate from this group, need a "reputation", and eventually a job.  The site is an ad for them and the more of what it displays of the results of the graduates, the more visitors will understand the "weight" of NU PRL.

**Comment by arjunguha** [comment]
How about this: limit the owners to the Contact Managers and Website Maintainers as defined here?

https://prl.ccs.neu.edu/contact.html

**Comment by ulysses4ever** [comment]
SGTM 

I would still leave couple faculty on the list just in case.

**Comment by bennn** [comment]
Thanks for restoring my access to `nuprl/amnesic`.

fwiw I liked the old policy much better: anyone can be an owner, as long as you're willing to be accountable and receive more github notifications.

**Comment by ulysses4ever** [comment]
It looks to me like closing this ticket is a bit early: the lab-members team still doesn’t have all the current members?

**Comment by camoy** [comment]
Should be up to date now.
