### ISSUE TITLE
Updates for 2022-2023

### ISSUE THREAD

**Issue by mhyee** [nuprl/website#311]
Various pages need updating, e.g. People, Teaching, Seminars, maybe Publications, Contact.

Not assigning anyone specific since the responsibilities are split up. [Here's the spreadsheet of this year's lab roles](https://docs.google.com/spreadsheets/d/1lLReRXcgMJvV0VIkA08p50BDeFiNg6RvU3H5VMSBoIU/edit#gid=0).

**Comment by ulysses4ever** [comment]
Since you’re writing about a split, maybe you could specify what’s the split exactly. I think it’s unfortunate that we don’t have a clear idea of who should update the website (nothing is more annoying that outdated info on the internets).

**Comment by ulysses4ever** [comment]
I just realized that it’s another split that I was thinking about. Sorry about the noise.

**Comment by mhyee** [comment]
People Page Maintainer (@a-wagner) should update the People page

Teaching / Software Page Maintainer (@a-wagner) should update the Teaching and Software pages

PL Seminar people (@john-ml @GouwarPower) should update the PL Seminar page

Publication Page maintainer (@katherine-hough) should update the Publications page

Contact Manager (@camoy) should update the Contact page

I don't know if there's anything else that should be updated; people should refer to the [spreadsheet](https://docs.google.com/spreadsheets/d/1lLReRXcgMJvV0VIkA08p50BDeFiNg6RvU3H5VMSBoIU/edit#gid=0) and the [Lab Roles](https://github.com/nuprl/website/wiki/Lab-Roles) page.

**Comment by mhyee** [comment]
Looks like everything is checked off, thanks all!
