### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by maxsnew** [nuprl/website#34]
I feel unmotivated to write cool blog posts without knowing about the tons of hits I'm getting.

I think it would be a great Christmas present for someone to set this up.
Supposedly Google analytics is pretty easy to set up, but I think @gasche wants something less evil.

**Comment by gasche** [comment]
I happen to have been thinking about this in the past few days, but the less-evil solutions are surprisingly bothersome to setup. I need a bit more time, but I hope to get it done next week.
