### ISSUE TITLE
Link to Twitter account

### ISSUE THREAD

**Issue by mhyee** [nuprl/website#35]
@schuster suggested this a while back, that the website should actually link to our Twitter.

The question is, where?

1. Beside "Programming Research Laboratory" on the front page (similar to the CCIS and Northeastern links)
2. On the Contact page (near the top? Bottom?)
3. On every page as a top-level link, beside Blog
4. Other?

Or some combination of the above.

I'm thinking at least 1. 3 might be too much.

**Comment by gasche** [comment]
3 seems natural to me. `Blog` takes me to the blog, `Twitter` takes me to the list of twitter posts.

**Comment by schuster** [comment]
I like 1. 3 is okay, but I'm not wild about a link that looks like it should stay in "this site" taking the reader somewhere else. If it's just on the Contact page, it will be buried.

No matter what you go with, I recommend *also* adding a step to the New Members page that mentions it, just to re-emphasize to new members that it exists.
