### ISSUE TITLE
Link to seminar notes

### ISSUE THREAD

**Issue by mhyee** [nuprl/website#36]
This is probably a browser-specific issue, but sometimes clicking the seminar notes links makes my browser download the markdown. (This happens for me on Firefox on macOS.) On Android, the notes are served as plain text.

Does this happen to anyone else? Is it a problem? (If not, we can just close this issue.)

One (simple?) fix is to link to the GitHub repo's copy of the file, where you get the markdown rendered for free. But this might be brittle, if GitHub changes how their links work.

**Comment by gasche** [comment]
"Served as plain text" is the intended semantics, we don't want to commit to respecting the markdown semantics -- and fixed-column spacing may be necessary in some cases, which I'm not sure rendered markdown provides.

I guess it's a matter of HTTP headers, but I am not sure we have control over this for github-hosted websites (otherwise PDF files served over github would just open instead of annoyingly force myself to "Save" them first.)

**Comment by bennn** [comment]
I think this is browser-specific, and we shouldn't worry. Someday they will render markdown like they do pdfs.

(related issue: I have to change my browser's encoding to UTF-8 to read them)

**Comment by mhyee** [comment]
I don't think we have control over the HTTP headers, and we can't do anything about browser behaviour.

I probably wasn't clear in the original post, but I meant linking to [this](https://github.com/nuprl/website/blob/master/seminar-notes/new-retractionsblame.md) version. We get the Markdown rendered, and if you use the GitHub syntax, you also get fixed-column spacing.

**Comment by gasche** [comment]
I understood that you meant this, but my issue was that many of the notes we took are not actually valid markdown, so they wouldn't render well (in particular fixed-column blocks may not be explicitly declared as here). I realize now that this is a somewhat silly criticism, as we can just use `.txt` for non-markdown-formatted (or partially-formatted) notes and nothing is lost -- github does seem to preserve fixed-column spacing and fonts for `.txt` files. That objection being lifted, I don't have any issue with the idea of linking to the github version -- and I like the argument that it encourages people (authors for example) to submit change proposals for clarification/whatever.

**Comment by bennn** [comment]
Ok, working on this now.
Can you think of anything besides `.md`, `.txt`, and `.html` that someone might want to write notes in? (Maybe `.org`?)

**Comment by gasche** [comment]
`.org` makes sense. We can also adjust the list dynamically as the need comes. (I don't think anyone in their right mind would write to write `html` directly, but they may compile their notes from something.)

**Comment by bennn** [comment]
Ok, added.
https://github.com/nuprl/website/commit/0f4df403c61be1e67a7e173f66e2c43a8362eb6d
