### ISSUE TITLE
bounce rate at 0 and cant figure out why

### ISSUE THREAD

**Issue by jmiro1** [nuprl/website#40]
Since December 2nd my bounce rate which was regularly around 20% plummeted to near 0%. Since then it has remained around 0%. I know this is impossible so I am trying to figure out what would make it do this?

Do any of you have an idea, or can you please point me in the right direction?

Website: https://lautrecouleur.com/

Thank you for your help,

Joaquim

**Comment by gasche** [comment]
Hi @jmiro1,

This issue does not make sense at all. Are you a confused human that got the wrong repository (if so, could you please explain how you ended up here and what was your reasoning, so that we can fix it) or a bot?

**Comment by jmiro1** [comment]
Hi,

Sorry I just started on github and figured I could ask the coding community
for some help figuring out why the tracking is not working properly on my
website...

Where should I post this type of question?

**Comment by gasche** [comment]
Github is a place where people collaborate on software project. The present repository `nuprl/website` is about the website of a specific research organization, it is not a place for discussion of websites in general. I don't know of parts of github that would act as question-answer sites; you are probably rather looking for [StackOverflow](http://stackoverflow.com/).

**Comment by jmiro1** [comment]
Hey,

Sorry about that then. Will check more closely next time before posting
randomly like that.

Best regards ,

Joaquim

**Comment by gasche** [comment]
No harm done, and good luck for your website endeavors.
