### ISSUE TITLE
Delete the .htpasswd file?

### ISSUE THREAD

**Issue by bennn** [nuprl/website#58]
Do we need this?
https://github.com/nuprl/website/blob/master/.htpasswd

If not, let's delete it.

**Comment by gasche** [comment]
We should delete `.htaccess` as well in this case.

The files came with Jan's initial push of the first website version in the github repository in August 2015. I suspect it's a remnant of something else that was never used.

**Comment by aatxe** [comment]
Seeing as the site is hosted on GitHub Pages and not Apache, both files ought to be doing nothing at all.

**Comment by LeifAndersen** [comment]
Ya. Jan originally hired out some chez people to make the website for us. They almost certainly put them in there in case we put it up on apache. :)

**Comment by bennn** [comment]
Czech people

**Comment by LeifAndersen** [comment]
omg...I've been using chez scheme too long...I didn't even realize I typed it instead of czech...thanks. :)
