### ISSUE TITLE
Add Aviral Goel

### ISSUE THREAD

**Issue by mhyee** [nuprl/website#64]
@aviralg also needs to be added to the organization.

Aviral, can you provide the following:

- [x] picture
- [x] advisor (Jan and Frank)
- [x] preferred email
- ~[ ] website?~
- [x] brief bio

**Comment by gasche** [comment]
See also: our [New Members](http://prl.ccs.neu.edu/new-members.html) webpage, which can be found from the website, and should be advertized to any new student or visiting student.

**Comment by mfelleisen** [comment]
It is beyond sad that you’re using @neu_prl.

**Comment by BenChung** [comment]
I've contacted Aviral directly for the relevant information. For some reason, Github notifications aren't getting emailed to me.

**Comment by aviralg** [comment]
Hi, I have added myself and created a pull request. This issue can be closed once its merged.
