### ISSUE TITLE
Race condition deploying the website

### ISSUE THREAD

**Issue by bennn** [nuprl/website#70]
Here's a bad thing that could happen:
1. pull requests A and B both target `nuprl/website`'s master branch
2. merge A, immediately merge B
3. builds for A and B start on `nuprl/nuprl.github.io`
4. the build for B finishes first & deploys
5. the build for A finishes second & deploys

Oh no! The changes from B are not deployed. Need to rebuild the site.

**Comment by bennn** [comment]
Email discussion:

@gasche 
> It's interesting (in a bad way) that we would have silent races when merging things too quickly.
> 
> Would it be possible for the build script to store the reference head commit at the time it starts building, and the one after it deployed, and restart the deployment if the two don't match?

@dbp 
> Restarting might be tricky, as I don't know if Travis has any way of a deploy script triggering that, but we probably can abort the deploy in the case that HEAD is not our commit. It'd have to happen in the deploy.sh script, which unfortunately is a little subtle. 

@gasche 
> > we probably can abort the deploy in the case that HEAD is not our commit. It'd have to happen in the deploy.sh script

> Checking before the deploy is not race-free, I think. It's better than the current situation, but your "git push deploy" could still be delayed for a while and have another merge in the meantime.

> > Restarting might be tricky, as I don't know if Travis has any way of a deploy script triggering that

> From deploy.sh you could just recursively call "sh ./deploy.sh" in the conditional. We would have to be fairly confident in our termination proof, though. It might be better to have an explicit loop in the script that keeps deploying while there is a mismatch, and fails after N rounds.

@dbp 
> It's a possible race, for sure, but I don't think it'll occur, because
there is a delay incurred by the build process.
> 
> i.e.,
> 
> Tree before:
> `*`
> 
> Commit a is merged:
> 
> `* --> a`
> 
> Build for a runs, checks to see if HEAD is still a (which is true).
> 
> (((
> Commit b is merged:
> 
> `* --> a --> b`
> 
> Build for b runs, checks to see if HEAD is still b (which is true).
>
> Deploy for b pushed.
> )))
> 
> Deploy for a pushed.
> 
> In order for that race to occur, the entirety between the ((( and )))
needs to occur between a checking and pushing, which is certainly
possible (arbitrary network delay), but seems quite unlikely, given that
builds take almost 2 minutes. i.e., the event streams are:
> 
> `push (fast)`
> `build (slow)`
> `check (fast)`
> `deploy (fast)`
>
> And in order to have the bad interleaving, between the check and the
deploy on one process, all four events have to happen on the other.
>
> Right?


@gasche 
> I realize now that the reason why "deploy, then check and restart" is a pain is that "restart" should fetch and restart the build, but the deploy script in theory is not in charge of building. So I guess the best approach would be to move the deployment responsibility to the install script, where it makes sense to have this restart logic. 

@bennn
> How about this recipe (TLDR, make the error non-silent):
> 
> 1. deploy remembers `git rev-parse HEAD`
> 2. deploy does its normal business, pushes ignorantly
> 3. deploy checks `git rev-parse HEAD~1` against the hash from step 1
> 4. if the commits don't match, report an issue to the `nuprl/website` repo

@dbp 
> I think we could do that (how easy is it to programaticly submit
issues?), though we might as well (while we're doing that) abort if we
detect we are racing. As in most cases, we would catch the race and
would avoid the problem entirely.
>
> To Gabriel: The race that results from this fix is
certainly possible, and, if we were merging commits all the time, at
high frequency, then yes, it might be a problem. But the thing is, it's
a self-correcting problem -- as whenever the next commit comes in, it
will fix the issue. Given that's the case (and the consequences of the
race are quite mundane), it seems worth doing.

**Comment by bennn** [comment]
(Will be closed by #69 )

**Comment by bennn** [comment]
Good news,
- I just merged 3 pull requests and triggered a race condition
- 2 of the 3 pull requests "failed to deploy", the last merged succeeded
- so the website currently shows the changes from all 3 PRs

Proof of the Travis failures on GitHub:
![screen shot 2017-04-28 at 17 32 45](https://cloud.githubusercontent.com/assets/1731829/25547986/551b1d7a-2c38-11e7-8c6f-0fb33018e4e8.png)


Detail view of a "failed to deploy" message:
![screen shot 2017-04-28 at 17 32 59](https://cloud.githubusercontent.com/assets/1731829/25547992/5ad32eec-2c38-11e7-8fb0-1599bcbc51d7.png)

**Comment by dbp** [comment]
Great! Thanks for "testing" it :)
