### ISSUE TITLE
Virtualbox Image file doesn't download

### ISSUE THREAD

**Issue by rmacnz** [nuprl/website#82]
Trying to download the image file for virtualbox from this tutorial results in downloading halfway and then an interruption occurs: http://prl.ccs.neu.edu/blog/2017/05/26/racket-6-9-and-windows-10-creators-update/

**Comment by gasche** [comment]
I just asked Leif, it seems that this issue cannot be reproduced, or rather (I'm sure we could find an unreliable network where that happens) that the non-issue can be reliably reproduced: downloading it generally works as well as downloading a big file from anywhere else. Closing.
