### ISSUE TITLE
Blog Comments

### ISSUE THREAD

**Issue by aatxe** [nuprl/website#98]
At @gasche's suggestion, we should probably add comments to the blog because otherwise all discussion is necessarily limited to Twitter. My opinion is that Disqus is a good option because the site is statically hosted, and we probably don't want to maintain our own comments back-end. It does, of course, have the disadvantage that it's proprietary and we don't really control it, but I've had positive experiences using it in the past.

**Comment by mhyee** [comment]
Disqus is certainly the most popular system for hosting comments, but it's proprietary and bad for privacy. (See also #43, #91.)

I found [an alternative](https://github.com/posativ/isso) but someone would need to host it.

**Comment by aatxe** [comment]
Another option (proposed by @tonyg on IRC) was [Talk](https://coralproject.github.io/talk/index.html) from Mozilla.

**Comment by LeifAndersen** [comment]
FWIW, hosting comments on our own server seems silly, especially because if we do that, we might as well just host the webpage itself. (Although I guess its less bad if only the comments go down, rather than the whole webpage).

Also I agree wrt. disqus. While it certainly is the most popular option...bleh.

With that being said, I don't really care about blog comments anyway, as they don't seem super valuable to me, so I personally don't care too much what we end up using.

**Comment by gasche** [comment]
Well the alternative to "people using disqus to comment" is "people using twitter to comment", and it's (1) just as proprietary, (2) just as bad for privacy, (3) not amenable to thought-out discussion, and (4) un-archivable and lost after a week. If we did add Disqus (or another alternative), some people would keep using Twitter for comments, but at least some content would stay close to the post and may encourage discussion.

I setup Disqus for my PhD lab blog and we did occasionally receive valuable comments. Random example: [Your first Coq plugin](http://gallium.inria.fr/blog/your-first-coq-plugin/).

**Comment by LeifAndersen** [comment]
>  Well the alternative to "people using disqus to comment" is "people using twitter to comment",

That is 'an' alternative, but not 'the' alternative.  For example, we _could_ use github for comments. In fact, I actually think that is a better idea than disquss. Because:

A) We can then export the comments should we choose to go to another platform.

B) Uhh...it makes me irrationally happier? I guess that's always a plus. ;)

**Comment by LeifAndersen** [comment]
Here is an example: http://hydroecology.net/using-github-to-host-blog-comments/

**Comment by LeifAndersen** [comment]
Oh, also, I tried it out on Video, and its actually not too bad: https://github.com/videolang/website/commit/c62a1c4585e3e60b015528e336a6007ddf7c866a

Also also, just look at the overhead disqus has: http://donw.io/post/github-comments/

**Comment by gasche** [comment]
Sure, I'm fine with other solutions than Disqus if someone is willing to put the work in to deploy them. Here I guess that means creating a new github repo for those comments, and sending a PR with the HTML magic to make it happen. @LeifAndersen, are you volunteering?

**Comment by LeifAndersen** [comment]
Nope. I still don't like blog comments in general. I have honestly never really seen them turn into a useful discussion.

**Comment by ulysses4ever** [comment]
I just saw a solution I thought about before (when reading this thread the first time): on-demand loading of Disqus. [See example](https://osa1.net/posts/2020-06-30-8-years-of-haskell.html) (in the bottom, there is the "Show comments" link that fires a JS action called  `loadDisqus`). I wonder if it would be tolerable by those who don't like Disqus or the whole idea of comments in general. 

I still miss the comments section becuase I see many interesting comment threads in personal blogs like Bob Harper's or Neel Krishnaswami's ones.

**Comment by mhyee** [comment]
I think this is a reasonable compromise.

**Comment by ulysses4ever** [comment]
[I posted a preview here](https://julia.prl.fit.cvut.cz/~artem/neu-prl-website/blog/2020/01/15/the-typed-racket-optimizer-vs-transient/) (due to paths messiness, my fork can't render Blog but this page I fixed manually).

**Comment by julbinb** [comment]
Oh, I like that preview!

**Comment by bennn** [comment]
#244
